### ISSUE TITLE
Variant calling error

### ISSUE THREAD

**Issue by davidcoffey** [mikessh/mageri#35]
Thank you for developing this useful tool!  While running Mageri v1.1.1 on targeted DNA sequencing files using the M3 mode, I get the following error:

[Wed Nov 22 16:11:50 PST 2017 +00m00s] [MM082417-102117] Started analysis.
[Wed Nov 22 16:11:51 PST 2017 +00m00s] [MM082417-102117] Pre-processing sample group HIP21692-PBMC.
[Wed Nov 22 16:11:51 PST 2017 +00m00s] [Indexer] Building UMI index, 0 reads processed, 0.0% extracted..
[Wed Nov 22 16:12:01 PST 2017 +00m10s] [Indexer] Building UMI index, 199489 reads processed, 94.24% extracted..
[Wed Nov 22 16:12:11 PST 2017 +00m20s] [Indexer] Building UMI index, 387165 reads processed, 93.59% extracted..
[Wed Nov 22 16:12:21 PST 2017 +00m30s] [Indexer] Building UMI index, 586867 reads processed, 76.88% extracted..
[Wed Nov 22 16:12:31 PST 2017 +00m40s] [Indexer] Building UMI index, 785330 reads processed, 73.68% extracted..
[Wed Nov 22 16:12:42 PST 2017 +00m51s] [Indexer] Building UMI index, 971652 reads processed, 77.15% extracted..
[Wed Nov 22 16:12:52 PST 2017 +01m01s] [Indexer] Building UMI index, 1168617 reads processed, 79.61% extracted..
[Wed Nov 22 16:13:02 PST 2017 +01m11s] [Indexer] Building UMI index, 1366130 reads processed, 77.72% extracted..
[Wed Nov 22 16:13:12 PST 2017 +01m21s] [Indexer] Building UMI index, 1564702 reads processed, 79.74% extracted..
[Wed Nov 22 16:13:22 PST 2017 +01m31s] [Indexer] Building UMI index, 1766735 reads processed, 80.94% extracted..
[Wed Nov 22 16:13:32 PST 2017 +01m41s] [Indexer] Building UMI index, 1961040 reads processed, 75.08% extracted..
[Wed Nov 22 16:13:44 PST 2017 +01m53s] [Indexer] Building UMI index, 2131529 reads processed, 73.28% extracted..
[Wed Nov 22 16:13:54 PST 2017 +02m03s] [Indexer] Building UMI index, 2336328 reads processed, 75.06% extracted..
[Wed Nov 22 16:14:04 PST 2017 +02m13s] [Indexer] Building UMI index, 2537257 reads processed, 76.46% extracted..
[Wed Nov 22 16:14:14 PST 2017 +02m23s] [Indexer] Building UMI index, 2731940 reads processed, 77.45% extracted..
[Wed Nov 22 16:14:17 PST 2017 +02m26s] [Indexer] Finished building UMI index, 2797028 reads processed, 76.17% extracted
[Wed Nov 22 16:14:17 PST 2017 +02m26s] [MM082417-102117] Running analysis for sample group HIP21692-PBMC.
[Wed Nov 22 16:14:17 PST 2017 +02m26s] [MM082417-102117.HIP21692-PBMC] Assembling & aligning consensuses, 0 MIGs processed..
[Wed Nov 22 16:14:27 PST 2017 +02m36s] [MM082417-102117.HIP21692-PBMC] Assembling & aligning consensuses, 34560 MIGs processed..
[Wed Nov 22 16:14:37 PST 2017 +02m46s] [MM082417-102117.HIP21692-PBMC] Assembling & aligning consensuses, 85098 MIGs processed..
[Wed Nov 22 16:14:44 PST 2017 +02m53s] [MM082417-102117.HIP21692-PBMC] Finished, 95639 MIGs processed in total.
[Wed Nov 22 16:14:44 PST 2017 +02m53s] [MM082417-102117.HIP21692-PBMC] Calling variants.
Exception in thread "main" java.lang.NoSuchMethodError: java.util.concurrent.ConcurrentHashMap.keySet()Ljava/util/concurrent/ConcurrentHashMap$KeySetView;
	at com.antigenomics.mageri.core.mapping.MutationsTable.getMutations(MutationsTable.java:170)
	at com.antigenomics.mageri.core.variant.VariantCaller.<init>(VariantCaller.java:80)
	at com.antigenomics.mageri.pipeline.analysis.SampleAnalysis.run(SampleAnalysis.java:152)
	at com.antigenomics.mageri.pipeline.analysis.ProjectAnalysis.run(ProjectAnalysis.java:111)
	at com.antigenomics.mageri.pipeline.Mageri.main(Mageri.java:129)

Do you have any suggestions as to what may be causing this error?

Thank you,

David

**Comment by mikessh** [comment]
Sorry for missing that. It is likely that the error stems from difference in Java version used to compile MAGERI https://github.com/AtlasOfLivingAustralia/ala-hub/issues/10. The binaries were compiled using Java v1.7

**Comment by davidcoffey** [comment]
I'm using Java version 1.7.0_51.  I just ran the analysis again, this time using different fastq files (much larger in size the prevous) and the parameter -Xmx64G and I get the following error:

...
[Thu Jan 18 08:54:07 PST 2018 +08m11s] [Indexer] Finished building UMI index, 9101205 reads processed, 100.0% extracted
[Thu Jan 18 08:54:07 PST 2018 +08m11s] [my_project] Running analysis for sample group my_sample.
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
        at java.util.concurrent.atomic.AtomicIntegerArray.<init>(AtomicIntegerArray.java:81)
        at com.antigenomics.mageri.core.mapping.NucleotideMatrix.<init>(NucleotideMatrix.java:35)
        at com.antigenomics.mageri.core.mapping.MutationsTable.<init>(MutationsTable.java:44)
        at com.antigenomics.mageri.core.mapping.ConsensusAligner.<init>(ConsensusAligner.java:60)
        at com.antigenomics.mageri.core.mapping.PConsensusAligner.<init>(PConsensusAligner.java:37)
        at com.antigenomics.mageri.core.mapping.PConsensusAlignerFactory.create(PConsensusAlignerFactory.java:34)
        at com.antigenomics.mageri.pipeline.analysis.PipelineConsensusAlignerFactory.create(PipelineConsensusAlignerFactory.java:53)
        at com.antigenomics.mageri.pipeline.analysis.ProjectAnalysis.run(ProjectAnalysis.java:107)
        at com.antigenomics.mageri.pipeline.Mageri.main(Mageri.java:129)
rhino1/fh/scratch/delete30/warren_h/dcoffey/DNAseq/DNAseq/MM082417-102117/mageri/log> java -v

**Comment by cez026** [comment]
I got the same error all the time using Java v1.7, even for the example one. 
Do you have any suggestion?

**Comment by mikessh** [comment]
Hello, this is an out-of-memory exception. You can

1) Increase the amount of memory using ``-Xmx`` parameter by running with, say, ``-Xmx128G``

or

2) Try to run for a subset of reads (``--limit``) 
3) Choose fewer/more specific references using custom FASTA and BED files as described in docs.
